[package]
edition = "2018"
name = "tact"
version = "0.1.0"
[dependencies]
actix-web = "3"
config = "*"
dotenv = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.rusqlite]
features = ["bundled"]
version = "0.24.1"
